# Generated by Django 3.1.7 on 2021-05-06 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default book title', max_length=100)),
                ('authors', models.CharField(default='Default author', max_length=100)),
                ('publisher', models.CharField(default='Default publisher', max_length=100)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_pages', models.IntegerField(default=0)),
                ('highlighted', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
