# Generated by Django 3.1.7 on 2021-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Default book title', max_length=100)),
                ('authors', models.CharField(blank=True, default='Default author', max_length=100)),
                ('publisher', models.CharField(blank=True, default='Default publisher', max_length=100)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_pages', models.IntegerField(default=0)),
            ],
        ),
    ]
